import {
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ChevronDown,
  ChevronLeft,
  Cog,
  CircleArrowUp,
  ExternalLink,
  GalleryVerticalEnd,
  ListFilter,
  Heart,
  House,
  LibraryBig,
  List,
  ListMusic,
  LogOut,
  MessageSquareQuote,
  MicVocal,
  Music2,
  Pause,
  Pencil,
  Play,
  Plus,
  Repeat,
  Search,
  Shuffle,
  SkipBack,
  SkipForward,
  Trash2,
  Upload,
  Volume2,
  VolumeX,
  X
} from "lucide-react";

export const icons = {
  album: GalleryVerticalEnd,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  artist: MicVocal,
  back: ChevronLeft,
  close: X,
  down: ChevronDown,
  edit: Pencil,
  externalLink: ExternalLink,
  filter: ListFilter,
  heart: Heart,
  home: House,
  library: LibraryBig,
  logout: LogOut,
  lyrics: MessageSquareQuote,
  music: Music2,
  pause: Pause,
  play: Play,
  plus: Plus,
  queue: List,
  playlist: ListMusic,
  repeat: Repeat,
  search: Search,
  settings: Cog,
  shuffle: Shuffle,
  skip: SkipForward,
  skipBack: SkipBack,
  trash: Trash2,
  update: CircleArrowUp,
  upload: Upload,
  volume: Volume2,
  volumeOff: VolumeX
};
