import {
  AudioWaveform,
  Boxes,
  ChevronDown,
  ChevronLeft,
  Cog,
  Heart,
  List,
  ListMusic,
  MessageSquareQuote,
  MicVocal,
  Music,
  Pause,
  Play,
  Repeat,
  Search,
  Shuffle,
  SkipBack,
  SkipForward,
  SquareStack,
  Trash2,
  Volume2,
  VolumeX
} from "lucide-react";

export const icons = {
  album: SquareStack,
  artist: MicVocal,
  back: ChevronLeft,
  down: ChevronDown,
  heart: Heart,
  home: AudioWaveform,
  library: Boxes,
  lyrics: MessageSquareQuote,
  music: Music,
  pause: Pause,
  play: Play,
  queue: List,
  playlist: ListMusic,
  repeat: Repeat,
  search: Search,
  settings: Cog,
  shuffle: Shuffle,
  skip: SkipForward,
  skipBack: SkipBack,
  trash: Trash2,
  volume: Volume2,
  volumeOff: VolumeX
};
